/* compress-probe: the Compression API (cabinet.dll) for test/compress-gate.sh.
 *
 *   compress-probe d IN OUT      Decompress an MSZIP buffer IN into OUT
 *   compress-probe c IN OUT      Compress IN (MSZIP, buffer mode) into OUT
 *   compress-probe r SIZE        round trip SIZE generated bytes; prints ok/FAIL
 *
 * Declared here (no compressapi.h needed from the SDK).
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */
#include <windows.h>
#include <stdio.h>
#include <stdlib.h>

BOOL WINAPI CreateDecompressor(DWORD, void *, HANDLE *);
BOOL WINAPI Decompress(HANDLE, const void *, SIZE_T, void *, SIZE_T, SIZE_T *);
BOOL WINAPI CloseDecompressor(HANDLE);
BOOL WINAPI CreateCompressor(DWORD, void *, HANDLE *);
BOOL WINAPI Compress(HANDLE, const void *, SIZE_T, void *, SIZE_T, SIZE_T *);
BOOL WINAPI CloseCompressor(HANDLE);

static BYTE *load( const char *path, SIZE_T *size )
{
    FILE *f = fopen( path, "rb" );
    BYTE *d;
    if (!f) return NULL;
    fseek( f, 0, SEEK_END ); *size = ftell( f ); fseek( f, 0, SEEK_SET );
    d = malloc( *size + 1 );
    *size = fread( d, 1, *size, f );
    fclose( f );
    return d;
}

static BOOL save( const char *path, const BYTE *d, SIZE_T size )
{
    FILE *f = fopen( path, "wb" );
    if (!f) return FALSE;
    fwrite( d, 1, size, f );
    fclose( f );
    return TRUE;
}

static BYTE *decompress( const BYTE *in, SIZE_T in_size, SIZE_T *out_size )
{
    HANDLE h;
    SIZE_T need = 0;
    BYTE *out;
    if (!CreateDecompressor( 2, NULL, &h )) { printf( "CreateDecompressor=%lu\n", GetLastError() ); return NULL; }
    if (Decompress( h, in, in_size, NULL, 0, &need ) || GetLastError() != ERROR_INSUFFICIENT_BUFFER)
    { printf( "query=%lu\n", GetLastError() ); return NULL; }
    out = malloc( need + 1 );
    if (!Decompress( h, in, in_size, out, need, out_size )) { printf( "Decompress=%lu\n", GetLastError() ); return NULL; }
    CloseDecompressor( h );
    return out;
}

static BYTE *compress( const BYTE *in, SIZE_T in_size, SIZE_T *out_size )
{
    HANDLE h;
    SIZE_T need = 0;
    BYTE *out;
    if (!CreateCompressor( 2, NULL, &h )) { printf( "CreateCompressor=%lu\n", GetLastError() ); return NULL; }
    if (Compress( h, in, in_size, NULL, 0, &need ) || GetLastError() != ERROR_INSUFFICIENT_BUFFER)
    { printf( "cquery=%lu\n", GetLastError() ); return NULL; }
    out = malloc( need + 1 );
    if (!Compress( h, in, in_size, out, need, out_size )) { printf( "Compress=%lu\n", GetLastError() ); return NULL; }
    CloseCompressor( h );
    return out;
}

int main( int argc, char **argv )
{
    SIZE_T in_size, out_size;
    BYTE *in, *out;

    if (argc < 3) return 2;
    if (argv[1][0] == 'r')
    {
        SIZE_T n = strtoul( argv[2], NULL, 10 ), csize, back, i;
        UINT32 seed = 7;
        BYTE *c, *b;
        in = malloc( n + 1 );
        for (i = 0; i < n; i++)   /* mixed: text-like runs and noise */
        {
            seed = seed * 1103515245 + 12345;
            in[i] = (i / 4096) % 3 ? "stained glass "[i % 14] : (BYTE)(seed >> 16);
        }
        if (!(c = compress( in, n, &csize )) || !(b = decompress( c, csize, &back ))) return 1;
        printf( "roundtrip%lu=%s\n", (unsigned long)n, back == n && !memcmp( in, b, n ) ? "ok" : "FAIL" );
        return 0;
    }
    if (argc < 4 || !(in = load( argv[2], &in_size ))) return 2;
    out = argv[1][0] == 'd' ? decompress( in, in_size, &out_size ) : compress( in, in_size, &out_size );
    if (!out || !save( argv[3], out, out_size )) return 1;
    printf( "%s=%lu\n", argv[1][0] == 'd' ? "decompressed" : "compressed", (unsigned long)out_size );
    return 0;
}
