#!/usr/bin/env python3
"""icons.py TREE -- Stained Glass OS's own file and folder icons, as SVG
sources in the Wine tree, rendered to .ico by build.sh (theme/images.list).

David: the folder and file icons "look old", a text file shows Wine's
notepad -- a wine glass with a pencil. These are our own flat drawings in
the Windows 10 manner: a manila folder, an open one, a page with a folded
corner, a text page with lines, and Notepad (a page under our accent band).

Each icon is one drawing on a 100-unit square, repeated at every size the
.ico carries (tools/buildimage cuts the rectangles named icon:SIZE-32). Line
widths are set per size in pixels, so the small sizes stay crisp and the
large ones do not look heavy. A new .ico gets an empty placeholder here, as
build.sh re-renders only files that exist.

Copyright (C) 2026 Stained Glass OS contributors; LGPL-2.1-or-later
"""
import os
import sys

SIZES = [256, 128, 96, 64, 48, 40, 32, 24, 20, 16]
GAP = 8

FOLDER_BACK = "#E3A92E"
FOLDER_FRONT = "#F7C948"
FOLDER_EDGE = "#C98D16"
FOLDER_LIGHT = "#FBDD85"
PAGE = "#FFFFFF"
PAGE_EDGE = "#8C8C8C"
PAGE_FOLD = "#E4E4E4"
LINE = "#A0A0A0"
ACCENT = "#7B3FD0"


def px(size, pixels):
    """a width of so many pixels at this size, in the 100-unit drawing"""
    return pixels * 100.0 / size


def stroke_px(size):
    return 1.0 if size <= 48 else size / 48.0


def folder(size, open_=False):
    sw = px(size, stroke_px(size))
    back = (f'<path d="M6 20 H38 L46 28 H94 V86 H6 Z" fill="{FOLDER_BACK}" '
            f'stroke="{FOLDER_EDGE}" stroke-width="{sw:.2f}" stroke-linejoin="round"/>')
    if open_:
        front = (f'<path d="M18 40 H98 L86 86 H6 Z" fill="{FOLDER_FRONT}" '
                 f'stroke="{FOLDER_EDGE}" stroke-width="{sw:.2f}" stroke-linejoin="round"/>')
        paper = f'<path d="M14 32 H86 V40 H14 Z" fill="{PAGE}"/>' if size >= 24 else ""
        return back + paper + front
    front = (f'<path d="M6 36 H94 V86 H6 Z" fill="{FOLDER_FRONT}" '
             f'stroke="{FOLDER_EDGE}" stroke-width="{sw:.2f}" stroke-linejoin="round"/>')
    light = ""
    if size >= 32:
        light = f'<path d="M{6 + sw:.2f} {36 + sw:.2f} H{94 - sw:.2f}" stroke="{FOLDER_LIGHT}" stroke-width="{sw:.2f}"/>'
    return back + front + light


def page(size, fold=True):
    sw = px(size, stroke_px(size))
    body = (f'<path d="M18 4 H62 L84 26 V96 H18 Z" fill="{PAGE}" stroke="{PAGE_EDGE}" '
            f'stroke-width="{sw:.2f}" stroke-linejoin="round"/>')
    corner = (f'<path d="M62 4 V26 H84 Z" fill="{PAGE_FOLD}" stroke="{PAGE_EDGE}" '
              f'stroke-width="{sw:.2f}" stroke-linejoin="round"/>') if fold else ""
    return body + corner


def text_lines(size, top, bottom, left=28, right=74, first_short=True):
    """lines of text, one or two pixels thick, snapped to pixel rows"""
    lw = px(size, 1.0 if size <= 32 else round(size / 32.0))
    step = max(px(size, 2 * (1.0 if size <= 32 else round(size / 32.0)) + (1 if size <= 24 else 2)), 8.0)
    out, y, i = [], top, 0
    while y <= bottom:
        r = right - 14 if (first_short and i % 3 == 2) else right
        out.append(f'<path d="M{left} {y:.2f} H{r}" stroke="{LINE}" stroke-width="{lw:.2f}"/>')
        y += step
        i += 1
    return "".join(out)


def text_document(size):
    return page(size) + text_lines(size, 38, 86)


def document(size):
    return page(size)


def notepad(size):
    sw = px(size, stroke_px(size))
    body = (f'<path d="M16 8 H84 V94 H16 Z" fill="{PAGE}" stroke="{PAGE_EDGE}" '
            f'stroke-width="{sw:.2f}" stroke-linejoin="round"/>')
    band = f'<path d="M16 8 H84 V26 H16 Z" fill="{ACCENT}"/>'
    rings = ""
    if size >= 32:
        for x in (30, 50, 70):
            rings += f'<circle cx="{x}" cy="17" r="{px(size, max(1.5, size / 20.0)):.2f}" fill="{PAGE}"/>'
    return body + band + rings + text_lines(size, 40, 86, left=26, right=74)


ICONS = {
    "dlls/shell32/resources/folder.svg": lambda s: folder(s),
    "dlls/shell32/resources/folder_open.svg": lambda s: folder(s, True),
    "dlls/shell32/resources/document.svg": document,
    "dlls/shell32/resources/sg_text.svg": text_document,
    "programs/notepad/notepad.svg": notepad,
}


def svg(draw):
    width = sum(SIZES) + GAP * (len(SIZES) - 1)
    height = max(SIZES)
    groups, rects, x = [], [], 0
    for s in SIZES:
        groups.append(f'<g transform="translate({x},0) scale({s / 100.0:.4f})">{draw(s)}</g>')
        rects.append(f'<rect id="icon:{s}-32" x="{x}" y="0" width="{s}" height="{s}" fill="none"/>')
        x += s + GAP
    return ('<?xml version="1.0" encoding="UTF-8" standalone="no"?>\n'
            '<!-- Stained Glass OS: generated by wine-sg theme/icons.py; our own drawing.\n'
            '     Copyright (C) 2026 Stained Glass OS contributors; LGPL-2.1-or-later -->\n'
            f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" version="1.1">\n'
            + "\n".join(groups) + "\n" + "\n".join(rects) + "\n</svg>\n")


def main(tree):
    for rel, draw in ICONS.items():
        path = os.path.join(tree, rel)
        with open(path, "w") as f:
            f.write(svg(draw))
        ico = path[:-4] + ".ico"
        if not os.path.exists(ico):
            open(ico, "wb").close()
        print(rel)


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else ".")
